services:
  # account-svc:
  #     container_name: account-svc
  #     image: edorguez/account-svc
  #     ports:
  #       - "${ACCOUNT_SVC_PORT}:${ACCOUNT_SVC_PORT}"
  #     env_file:
  #       - /env/account.env
  #     depends_on:
  #       - account-db
  #     restart: always
  #
  # alert-svc:
  #     container_name: alert-svc
  #     image: edorguez/alert-svc
  #     ports:
  #       - "${ALERT_SVC_PORT}:${ALERT_SVC_PORT}"
  #     env_file:
  #       - /env/alert.env
  #     depends_on:
  #       - alert-db
  #     restart: always
  #

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.9.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    restart: always

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.9.0
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  account-db:
    container_name: account-db
    image: postgres:17.4
    env_file:
      - ./env/account.env
    ports:
      - "${ACCOUNT_DB_PORT}:5432"
    volumes:
      - account-db-data:/var/lib/postgresql/data
    restart: always

  alert-db:
    container_name: alert-db
    image: postgres:17.4
    env_file:
      - ./env/alert.env
    ports:
      - "${ALERT_DB_PORT}:5432"
    volumes:
      - alert-db-data:/var/lib/postgresql/data 
    restart: always

  alert-user-cache:
    container_name: alert-user-cache
    image: redis:7.4.2
    ports:
      - "${ALERT_USER_CACHE_REDIS_PORT}:6379"
    volumes:
      - alert-user-cache-data:/data
    restart: always

volumes:
  account-db-data:
  alert-db-data:
  alert-user-cache-data:
