services:
  # account-svc:
  #     container_name: account-svc
  #     image: edorguez/account-svc
  #     ports:
  #       - "${ACCOUNT_SVC_PORT}:${ACCOUNT_SVC_PORT}"
  #     env_file:
  #       - /env/account.env
  #     depends_on:
  #       - account-db
  #     restart: always
  #
  # alert-svc:
  #     container_name: alert-svc
  #     image: edorguez/alert-svc
  #     ports:
  #       - "${ALERT_SVC_PORT}:${ALERT_SVC_PORT}"
  #     env_file:
  #       - /env/alert.env
  #     depends_on:
  #       - alert-db
  #     restart: always

  account-db:
    container_name: account-db
    image: postgres:17.4
    env_file:
      - ./env/account.env
    ports:
      - "${ACCOUNT_DB_PORT}:5432"
    restart: always

  alert-db:
    container_name: alert-db
    image: postgres:17.4
    env_file:
      - ./env/alert.env
    ports:
      - "${ALERT_DB_PORT}:5432"
    restart: always
