// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/edorguez/payment-reminder/internal/alert/models"
	mock "github.com/stretchr/testify/mock"
)

// MockAlertTemplateRepository is an autogenerated mock type for the AlertTemplateRepository type
type MockAlertTemplateRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockAlertTemplateRepository) FindByID(ctx context.Context, id int64) (*models.AlertTemplate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.AlertTemplate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.AlertTemplate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.AlertTemplate); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AlertTemplate)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockAlertTemplateRepository creates a new instance of MockAlertTemplateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAlertTemplateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAlertTemplateRepository {
	mock := &MockAlertTemplateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
