// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/edorguez/payment-reminder/internal/alert/repository"
	mock "github.com/stretchr/testify/mock"
)

// MockUserCacheRepository is an autogenerated mock type for the UserCacheRepository type
type MockUserCacheRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserCacheRepository) Create(ctx context.Context, user repository.UserCache) (*int64, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UserCache) (*int64, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UserCache) *int64); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UserCache) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockUserCacheRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockUserCacheRepository) FindByID(ctx context.Context, id int64) (*repository.UserCache, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *repository.UserCache
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*repository.UserCache, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *repository.UserCache); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.UserCache)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserCacheRepository) Update(ctx context.Context, user repository.UserCache) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UserCache) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockUserCacheRepository creates a new instance of MockUserCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCacheRepository {
	mock := &MockUserCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
